blank_issues_enabled: false
contact_links:
  - name: Questions / Discussions
    url: https://github.com/kenika/multi-calendar-grid-card/discussions
    about: Ask questions or discuss ideas here first.
